# Generated by Django 3.0.6 on 2020-06-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'armstate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'gui',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lockstate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'lockstate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'pincode',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pininput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'pininput',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RfidId',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(blank=True, max_length=70, null=True)),
                ('code', models.CharField(max_length=20)),
                ('datecreated', models.DateTimeField()),
            ],
            options={
                'db_table': 'rfid_id',
                'managed': False,
            },
        ),
    ]
