# Generated by Django 3.0.6 on 2020-06-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armstate',
            options={'managed': True},
        ),
    ]
