# Generated by Django 3.0.6 on 2020-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20200601_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidId',
            fields=[
                ('entryid', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.CharField(blank=True, max_length=70, null=True)),
                ('code', models.CharField(max_length=20)),
                ('datecreated', models.DateTimeField()),
            ],
            options={
                'db_table': 'rfid_id',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Armstate',
        ),
    ]
