# Generated by Django 3.0.6 on 2020-06-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20200601_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RfidId',
        ),
    ]
